### ISSUE TITLE
恕我直言，你这是抄袭

### ISSUE THREAD

**Issue by pwyq** [HuTianQi/CircleProgressBar#1]
原址：https://github.com/Todd-Davies/ProgressWheel
翻译了，改了变量名就变成了自己的东西了？还真好意思用MIT License。
你其他的projects也可以看出各种抄袭痕迹，真不想一一点破了。请尊重一下原作者。

**Comment by HuTianQi** [comment]
请你看清楚代码逻辑后再做评价可以吗？最核心的地方是wrap_content的自适应。其余的地方任何一个自定义控件的步骤都一样。
